In [38]:
import pandas as pd

In [45]:
data = pd.read_csv('Appendix D_ OutreachCallsSourceData2.xlsx - OutreachCallsSourceData2.csv')

c:\Users\16195\anaconda3\envs\dsc80\lib\site-packages\IPython\core\interactiveshell.py:3378: DtypeWarning: Columns (1,2,4,34,35,36,37,38) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [46]:
data.head()

,count,ProjectName,OfficePhoneNumber,email,website,parcelnumb,owner,address,scity,szip,usecode,ll_bldg_footprint_sqft,ll_bldg_count,parval,owner2,mailadd,careof,ownerocc,unitqty,asr_landuse,asr_zone,year_effec,total_lvg_,bedrooms,baths,addition_a,garage_con,garage_sta,carport_st,pool,usable_sq_,overlay_ju,ll_gisacre,qoz,phone,BROOMS,HAccess,PrefCLt,Waitlist,fromREGRID,fromCounty,fromScraping
0,6366,9951 Dolores St Spring Valley; CA 91977 - Apar...,(209) 764-0077,NaN,https://www.apartments.com/9951-dolores-st-spr...,5012470100,ROSS FAMILY TRUST 02-26-99,9951 DOLORES ST,SPRING VALLEY,91977-1542,1200.0,5209.0,2.0,659925.0,NaN,4554 LIMERICK WAY SAN DIEGO CA 92117,NaN,NaN,8.0,14,3.0,1989.0,8532.0,22.0,17.0,53750.0,NaN,999.0,NaN,NaN,NaN,CN,0.29335,No,NaN,NaN,NaN,NaN,NaN,1,NaN,1.0
1,12411,NaN,(442) 245-5178,NaN,NaN,1690111200,SOUTHRIDGE-OXFORD LTD PARTNERSHIP,3500 WINDRIFT WAY,OCEANSIDE,92056-5201,1200.0,280068.0,87.0,41654694.0,NaN,13155 NOEL RD #100LB73 DALLAS TX 75240,C/O RYAN; LLC THREE GALLERIA TOWER,NaN,404.0,16,3.0,1988.0,99999.0,NaN,NaN,0.0,N,865.0,76.0,Y,99999.0,OC,24.08459,No,NaN,NaN,NaN,NaN,NaN,1,NaN,1.0
2,12389,NaN,(442) 245-5429,NaN,NaN,1614901300,LAKERIDGE-ISLAND CLUB APTS PARTNERS LP,2300 CATALINA CIR,OCEANSIDE,92056-5301,1200.0,221180.0,73.0,41013219.0,NaN,13155 NOEL DR #100 DALLAS TX 75240,C/O RYAN LLC,NaN,336.0,16,3.0,1988.0,99999.0,NaN,NaN,0.0,N,776.0,77.0,Y,99999.0,OC,14.05518,No,NaN,NaN,NaN,NaN,NaN,1,NaN,1.0
3,12338,NaN,(442) 245-5429,NaN,NaN,1614901200,LAKERIDGE-ISLAND CLUB APTS PARTNERS LP,2401 CATALINA CIR,OCEANSIDE,92056-5350,1200.0,169385.0,52.0,31248159.0,NaN,13155 NOEL DR #100 DALLAS TX 75240,C/O RYAN LLC,NaN,256.0,16,3.0,1988.0,99999.0,NaN,NaN,0.0,N,776.0,77.0,Y,99999.0,OC,10.56498,No,NaN,NaN,NaN,NaN,NaN,1,NaN,1.0
4,10920,NaN,(442) 248-8207,NaN,NaN,2291603000,3630 BAYSIDE L L C,624 E MISSION AVE,ESCONDIDO,92025-2048,1200.0,29270.0,11.0,5860724.0,NaN,745 COAST BLVD S #1A LA JOLLA CA 92037,NaN,NaN,38.0,15,3.0,1973.0,38518.0,0.0,0.0,38005.0,NaN,NaN,NaN,NaN,NaN,ES,1.75535,No,NaN,NaN,NaN,NaN,NaN,1,NaN,1.0

In [47]:
data.dropna(subset=[' address'], inplace=True)

In [56]:
pd.set_option('display.max_columns', None)
data[data[' address'].str.contains('NOBEL')]

,count,ProjectName,OfficePhoneNumber,email,website,parcelnumb,owner,address,scity,szip,usecode,ll_bldg_footprint_sqft,ll_bldg_count,parval,owner2,mailadd,careof,ownerocc,unitqty,asr_landuse,asr_zone,year_effec,total_lvg_,bedrooms,baths,addition_a,garage_con,garage_sta,carport_st,pool,usable_sq_,overlay_ju,ll_gisacre,qoz,phone,BROOMS,HAccess,PrefCLt,Waitlist,fromREGRID,fromCounty,fromScraping
1599,12349,NaN,(858) 452-3622,NaN,NaN,3451903500,NOBEL COURT L P,3707 NOBEL DR,SAN DIEGO,92122-4589,1200.0,106800.0,4.0,73825389.0,NaN,3444 CAMINO DE RIO N #202 SAN DIEGO CA 92108,NaN,NaN,267.0,16,4.0,1987.0,99999.0,0.0,0.0,99999.0,NaN,0.0,0.0,NaN,0.0,SD,4.61432,No,NaN,NaN,NaN,NaN,NaN,1,NaN,1.0
1649,11428,NaN,(858) 558-1678,NaN,NaN,3487500100,WHISPERING PINES NOBEL LLC,4085 NOBEL DR,SAN DIEGO,92122-5867,1200.0,35088.0,17.0,1868937.0,NaN,4627 RUFFNER ST SAN DIEGO CA 92111,C/O CAL WEST MANAGEMENT ENTERPRIS,NaN,60.0,15,2.0,2000.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,SD,1.90293,No,NaN,NaN,NaN,NaN,NaN,1,NaN,1.0
1674,11117,NaN,(858) 638-0105,NaN,NaN,3487500200,LA JOLLA NOBEL L P,4149 NOBEL DR,SAN DIEGO,92122-1105,1200.0,17024.0,3.0,4159547.0,NaN,9948 HIBERT ST #210 SAN DIEGO CA 92131,WILLMARK COMMUNITIES INC,NaN,44.0,16,3.0,1977.0,27294.0,82.0,7.9,52917.0,N,620.0,82.0,Y,66640.0,SD,1.50115,No,NaN,NaN,NaN,NaN,NaN,1,NaN,1.0
28061,12399,NaN,NaN,NaN,NaN,3451203500,LA JOLLA INTERNATIONAL LTD,3899 NOBEL DR,SAN DIEGO,92122-5757,1200.0,93300.0,4.0,38858469.0,NaN,8899 UNIVERSITY CENTER LN #300 SAN DIEGO CA 92122,C/O LOMCO MGMT,NaN,354.0,16,3.0,2000.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,SD,4.07033,No,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
31030,11499,NaN,NaN,NaN,NaN,3487500300,LA JOLLA NOBEL L P,4249 NOBEL DR,SAN DIEGO,92122-1113,1200.0,31209.0,3.0,6604999.0,NaN,9948 HIBERT ST #210 SAN DIEGO CA 92131,WILLMARK COMMUNITIES INC,NaN,64.0,16,3.0,1977.0,43108.0,82.0,7.9,52917.0,N,674.0,82.0,Y,94960.0,SD,2.22835,No,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN

In [59]:
data[data[' address'] == '4249 NOBEL DR']

,count,ProjectName,OfficePhoneNumber,email,website,parcelnumb,owner,address,scity,szip,usecode,ll_bldg_footprint_sqft,ll_bldg_count,parval,owner2,mailadd,careof,ownerocc,unitqty,asr_landuse,asr_zone,year_effec,total_lvg_,bedrooms,baths,addition_a,garage_con,garage_sta,carport_st,pool,usable_sq_,overlay_ju,ll_gisacre,qoz,phone,BROOMS,HAccess,PrefCLt,Waitlist,fromREGRID,fromCounty,fromScraping
31030,11499,NaN,NaN,NaN,NaN,3487500300,LA JOLLA NOBEL L P,4249 NOBEL DR,SAN DIEGO,92122-1113,1200.0,31209.0,3.0,6604999.0,NaN,9948 HIBERT ST #210 SAN DIEGO CA 92131,WILLMARK COMMUNITIES INC,NaN,64.0,16,3.0,1977.0,43108.0,82.0,7.9,52917.0,N,674.0,82.0,Y,94960.0,SD,2.22835,No,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN

In [60]:
data[data[' address'] == '4149 NOBEL DR']

,count,ProjectName,OfficePhoneNumber,email,website,parcelnumb,owner,address,scity,szip,usecode,ll_bldg_footprint_sqft,ll_bldg_count,parval,owner2,mailadd,careof,ownerocc,unitqty,asr_landuse,asr_zone,year_effec,total_lvg_,bedrooms,baths,addition_a,garage_con,garage_sta,carport_st,pool,usable_sq_,overlay_ju,ll_gisacre,qoz,phone,BROOMS,HAccess,PrefCLt,Waitlist,fromREGRID,fromCounty,fromScraping
1674,11117,NaN,(858) 638-0105,NaN,NaN,3487500200,LA JOLLA NOBEL L P,4149 NOBEL DR,SAN DIEGO,92122-1105,1200.0,17024.0,3.0,4159547.0,NaN,9948 HIBERT ST #210 SAN DIEGO CA 92131,WILLMARK COMMUNITIES INC,NaN,44.0,16,3.0,1977.0,27294.0,82.0,7.9,52917.0,N,620.0,82.0,Y,66640.0,SD,1.50115,No,NaN,NaN,NaN,NaN,NaN,1,NaN,1.0